// ATLCOMService.idl : IDL source for ATLCOMService
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLCOMService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(6FD5305A-A8D9-468C-8DE8-56A9D0C6048D),
	version(1.0),
]
library ATLCOMServiceLib
{
	importlib("stdole2.tlb");
};

